variables:
  CI_SCRIPTS_DIR: "./ci"

gift-gala:
  script:
    - "$CI_SCRIPTS_DIR/test-mac.sh"
  tags:
    - gift-gala
    - gift-mac
    - matlab
    - cuda

gift-adelie:
  script:
    - "$CI_SCRIPTS_DIR/test-linux.sh"
  tags:
    - gift-adelie
    - gift-linux
    - matlab
    - cuda

gift-skylight:
  script:
    - set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
    - "call .\\ci\\test-win.bat"
  tags:
    - gift-skylight
    - gift-win64
    - matlab
    - cuda

