variables:
  CI_SCRIPTS_DIR: "./ci"

gift-gala-cuda7:
  script:
    - MATLAB_EXE=/Applications/MATLAB_R2016b.app/bin/matlab
    - MATLAB_SCRIPT=$(pwd)/matlab/CIBuildAndTest.m
    - XCODE_EXE=/Applications/Xcode7.3.1.app/Contents/Developer
    - PATH_WITH_CUDA=/Developer/NVIDIA/CUDA-7.5/bin${PATH:+:${PATH}}
    - env DEVELOPER_DIR=$XCODE_EXE PATH=$PATH_WITH_CUDA $CI_SCRIPTS_DIR/test-mac.sh $MATLAB_EXE $MATLAB_SCRIPT
  tags:
    - gift-gala
    - gift-mac
    - matlab-r2016b
    - cuda-7

gift-gala-cuda8:
  script:
    - MATLAB_EXE=/Applications/MATLAB_R2017a.app/bin/matlab
    - MATLAB_SCRIPT=$(pwd)/matlab/CIBuildAndTest.m
    - XCODE_EXE=/Applications/Xcode7.3.1.app/Contents/Developer
    - PATH_WITH_CUDA=/Developer/NVIDIA/CUDA-8.0/bin${PATH:+:${PATH}}
    - env DEVELOPER_DIR=$XCODE_EXE PATH=$PATH_WITH_CUDA $CI_SCRIPTS_DIR/test-mac.sh $MATLAB_EXE $MATLAB_SCRIPT
  tags:
    - gift-gala
    - gift-mac
    - matlab-r2017a
    - cuda-8

gift-adelie:
  script:
    - MATLAB_EXE=/usr/local/R2015b/bin/matlab
    - MATLAB_SCRIPT=$(pwd)/matlab/CIBuildAndTest.m
    - LD_PRELOAD_DIR=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
    - PATH_WITH_CUDA=/usr/local/cuda-7.5/bin${PATH:+:${PATH}}
    - env LD_PRELOAD=$LD_PRELOAD_DIR CORE_CXX=/usr/bin/g++-4.7 PATH=$PATH_WITH_CUDA $CI_SCRIPTS_DIR/test-linux.sh $MATLAB_EXE $MATLAB_SCRIPT
  tags:
    - gift-adelie
    - gift-linux
    - matlab
    - cuda-7

gift-skylight:
  script:
    - set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
    - "call .\\ci\\test-win.bat"
  tags:
    - gift-skylight
    - gift-win64
    - matlab
    - cuda

