variables:
  CI_SCRIPTS_DIR: "./ci"

gift-gala:
  script:
    - MATLAB_SCRIPT=$(pwd)/matlab/CIBuildAndTest.m
    - echo "***** CUDA 7 *****"
    - MATLAB_EXE=/Applications/MATLAB_R2016b.app/bin/matlab
    - XCODE_EXE=/Applications/Xcode7.3.1.app/Contents/Developer
    - PATH_WITH_CUDA=/Developer/NVIDIA/CUDA-7.5/bin${PATH:+:${PATH}}
    - env DEVELOPER_DIR=$XCODE_EXE PATH=$PATH_WITH_CUDA $CI_SCRIPTS_DIR/test-mac.sh $MATLAB_EXE $MATLAB_SCRIPT
    - echo "***** CUDA 8 *****"
    - MATLAB_EXE=/Applications/MATLAB_R2017a.app/bin/matlab
    - XCODE_EXE=/Applications/Xcode7.3.1.app/Contents/Developer
    - PATH_WITH_CUDA=/Developer/NVIDIA/CUDA-8.0/bin${PATH:+:${PATH}}
  tags:
    - gift-gala
    - gift-mac
    - matlab
    - cuda

gift-adelie:
  script:
    - MATLAB_SCRIPT=$(pwd)/matlab/CIBuildAndTest.m
    - echo "***** CUDA 7 *****"
    - MATLAB_EXE=/usr/local/R2015b/bin/matlab
    - PATH_WITH_CUDA=/usr/local/cuda-7.5/bin${PATH:+:${PATH}}
    - LD_PRELOAD_DIR=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
    - env LD_PRELOAD=$LD_PRELOAD_DIR CORE_CXX=/usr/bin/g++-4.7 PATH=$PATH_WITH_CUDA $CI_SCRIPTS_DIR/test-linux.sh $MATLAB_EXE $MATLAB_SCRIPT
    - echo "***** CUDA 8 *****"
    - MATLAB_EXE=/usr/local/R2017a/bin/matlab
    - PATH_WITH_CUDA=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
    - LD_PRELOAD_DIR=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
    - env LD_PRELOAD=$LD_PRELOAD_DIR CORE_CXX=/usr/bin/g++-4.9 PATH=$PATH_WITH_CUDA $CI_SCRIPTS_DIR/test-linux.sh $MATLAB_EXE $MATLAB_SCRIPT
  tags:
    - gift-adelie
    - gift-linux
    - matlab
    - cuda

gift-skylight:
  script:
    - set OLD_PATH=%PATH%
    - echo ***** CUDA 7 *****
    - set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
    - set PATH=%CUDA_PATH%\bin;%OLD_PATH%;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
    - "call .\\ci\\test-win.bat"
    - echo ***** CUDA 8 *****
    - set CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
    - set PATH=%CUDA_PATH%\bin;%OLD_PATH%;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
    - "call .\\ci\\test-win.bat"
  tags:
    - gift-skylight
    - gift-win64
    - matlab
    - cuda

